[general]
import = [
	"~/.config/alacritty/catppuccin-frappe.toml"
]

[window]
decorations = "None"
startup_mode = "Maximized"
opacity = 0.8
blur = true

[font.normal]
family = "JetBrainsMono Nerd Font"

[terminal.shell]
program = "/bin/zsh"
